### ISSUE TITLE
nodes.txt was removed with last commit

### ISSUE THREAD

**Issue by hobeika** [sfan5/mt2obj#2]
Hi,

In your last commit you have added the nodes.txt file to the .ignore list and thus it was removed from the repository.
Could you please restore it? Or is there another way to use this program without the nodes.txt file?

Thanks!

**Comment by sfan5** [comment]
Yes, you are supposed to generate a nodes.txt yourself using the code in the `nodedef_gen` folder.
No idea if that still works and I don't plan to work on this.

> Could you please restore it?

You can still view the old file here: https://github.com/sfan5/mt2obj/blob/bd1e45fe269e87dc7157ee61becd5c97bffc439a/nodes.txt

**Comment by vincent-hobeika-sonarsource** [comment]
Thanks for the explanation! I'll try.
You can close this issue then.

**Comment by hobeika** [comment]
Thanks for the explanations.
I'll try this.
